# Generated by Django 4.2.4 on 2023-11-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='money_for_financial',
        ),
    ]
