# Generated by Django 4.2.4 on 2023-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='money_for_financial',
            field=models.IntegerField(default=0),
        ),
    ]
