# Generated by Django 4.2.4 on 2023-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='left_money_for_financial',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='used_money_for_financial',
            field=models.IntegerField(default=0),
        ),
    ]
