# Generated by Django 4.2.4 on 2023-11-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('dcls_end_day', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(null=True, unique=True)),
                ('fin_co_no', models.TextField(null=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_way', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('dcls_end_day', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('fin_prdt_cd', models.TextField(null=True)),
                ('kor_co_nm', models.TextField(null=True)),
                ('fin_prdt_nm', models.TextField(null=True)),
                ('max_limit', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('dcls_end_day', models.TextField(null=True)),
                ('rsrv_type', models.TextField(null=True)),
                ('rsrv_type_nm', models.TextField(null=True)),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('rsrv_type', models.TextField(null=True)),
                ('rsrv_type_nm', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financial_data.savingproduct', to_field='fin_prdt_cd')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='financial_data.depositproduct', to_field='fin_prdt_cd')),
            ],
        ),
    ]
