# Generated by Django 4.2.4 on 2023-11-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedSaving',
        ),
    ]
